export default {
	emjoyList: {
		"[emjoy_01]": 'public/static/img/emjoy/emjoy_01.gif',
		"[emjoy_02]": 'public/static/img/emjoy/emjoy_02.gif',
		"[emjoy_03]": 'public/static/img/emjoy/emjoy_03.gif',
		"[emjoy_04]": 'public/static/img/emjoy/emjoy_04.gif',
		"[emjoy_05]": 'public/static/img/emjoy/emjoy_05.gif',
		"[emjoy_06]": 'public/static/img/emjoy/emjoy_06.gif',
		"[emjoy_07]": 'public/static/img/emjoy/emjoy_07.gif',
		"[emjoy_08]": 'public/static/img/emjoy/emjoy_08.gif',
		"[emjoy_09]": 'public/static/img/emjoy/emjoy_09.gif',

		"[emjoy_10]": 'public/static/img/emjoy/emjoy_10.gif',
		"[emjoy_11]": 'public/static/img/emjoy/emjoy_11.gif',
		"[emjoy_12]": 'public/static/img/emjoy/emjoy_12.gif',
		"[emjoy_13]": 'public/static/img/emjoy/emjoy_13.gif',
		"[emjoy_14]": 'public/static/img/emjoy/emjoy_14.gif',
		"[emjoy_15]": 'public/static/img/emjoy/emjoy_15.gif',
		"[emjoy_16]": 'public/static/img/emjoy/emjoy_16.gif',
		"[emjoy_17]": 'public/static/img/emjoy/emjoy_17.gif',
		"[emjoy_18]": 'public/static/img/emjoy/emjoy_18.gif',
		"[emjoy_19]": 'public/static/img/emjoy/emjoy_19.gif',

		"[emjoy_20]": 'public/static/img/emjoy/emjoy_20.gif',
		"[emjoy_21]": 'public/static/img/emjoy/emjoy_21.gif',
		"[emjoy_22]": 'public/static/img/emjoy/emjoy_22.gif',
		"[emjoy_23]": 'public/static/img/emjoy/emjoy_23.gif',
		"[emjoy_24]": 'public/static/img/emjoy/emjoy_24.gif',
		"[emjoy_25]": 'public/static/img/emjoy/emjoy_25.gif',
		"[emjoy_26]": 'public/static/img/emjoy/emjoy_26.gif',
		"[emjoy_27]": 'public/static/img/emjoy/emjoy_27.gif',
		"[emjoy_28]": 'public/static/img/emjoy/emjoy_28.gif',
		"[emjoy_29]": 'public/static/img/emjoy/emjoy_29.gif',

		"[emjoy_30]": 'public/static/img/emjoy/emjoy_30.gif',
		"[emjoy_31]": 'public/static/img/emjoy/emjoy_31.gif',
		"[emjoy_32]": 'public/static/img/emjoy/emjoy_32.gif',
		"[emjoy_33]": 'public/static/img/emjoy/emjoy_33.gif',
		"[emjoy_34]": 'public/static/img/emjoy/emjoy_34.gif',
		"[emjoy_35]": 'public/static/img/emjoy/emjoy_35.gif',
		"[emjoy_36]": 'public/static/img/emjoy/emjoy_36.gif',
		"[emjoy_37]": 'public/static/img/emjoy/emjoy_37.gif',
		"[emjoy_38]": 'public/static/img/emjoy/emjoy_38.gif',
		"[emjoy_39]": 'public/static/img/emjoy/emjoy_39.gif',

		"[emjoy_40]": 'public/static/img/emjoy/emjoy_40.gif',
		"[emjoy_41]": 'public/static/img/emjoy/emjoy_41.gif',
		"[emjoy_42]": 'public/static/img/emjoy/emjoy_42.gif',
		"[emjoy_43]": 'public/static/img/emjoy/emjoy_43.gif',
		"[emjoy_44]": 'public/static/img/emjoy/emjoy_44.gif',
		"[emjoy_45]": 'public/static/img/emjoy/emjoy_45.gif',
		"[emjoy_46]": 'public/static/img/emjoy/emjoy_46.gif',
		"[emjoy_47]": 'public/static/img/emjoy/emjoy_47.gif',
	}
}
